on:
  push:
    branches:
     - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Run react build script
        run: yarn && yarn build
        env:
          CI: false
          
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.0.0
      with:
        server: ftp.paudelanuj.com.np
        username: ftp_github@paudelanuj.com.np
        password: ${{ secrets.FTP_PASSWORD }}